CREATE DATABASE F1SimulatorDBTeamManegementService
GO

USE F1SimulatorDBTeamManegementService
GO

CREATE TABLE Teams(
    TeamId UNIQUEIDENTIFIER PRIMARY KEY  NOT NULL,
    [Name] VARCHAR(50) NOT NULL,
    NameAcronym VARCHAR(10) NOT NULL,
    Country VARCHAR(50) NOT NULL
);

CREATE TABLE Boss(
    BossId UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    TeamId UNIQUEIDENTIFIER NOT NULL,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Age INT NOT NULL
);

CREATE TABLE Engineers(
    EngineerId UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    TeamId UNIQUEIDENTIFIER NOT NULL,
    CarId UNIQUEIDENTIFIER NOT NULL,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Specialization VARCHAR(2) 
    CHECK (Specialization IN ('Ca', 'Cp')) NOT NULL,
    IsActive BIT NOT NULL
);

CREATE TABLE Cars(
    CarId UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    TeamId UNIQUEIDENTIFIER NOT NULL,
    Model Char(5) NOT NULL,
    WeightKg NUMERIC(6,2) NOT NULL,
    Speed INTEGER NOT NULL,
    Ca NUMERIC(4,3) NOT NULL,
    Cp NUMERIC(4,3) NOT NULL
);

CREATE TABLE [Drivers] (
	DriverNumber UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	TeamId UNIQUEIDENTIFIER NOT NULL,
	CarId UNIQUEIDENTIFIER NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	FullName VARCHAR(50) NOT NULL,
	NameAcronym VARCHAR(10) NOT NULL,
	WeightKg NUMERIC(5,2) NOT NULL,
	HandiCap NUMERIC(5,2) NOT NULL,
	IsActive BIT NOT NULL
);

ALTER TABLE [Engineers]
ADD FOREIGN KEY([TeamId])
REFERENCES [Teams]([TeamId])
GO

ALTER TABLE [Boss]
ADD FOREIGN KEY([TeamId])
REFERENCES [Teams]([TeamId])
GO

ALTER TABLE [Cars]
ADD FOREIGN KEY([TeamID])
REFERENCES [Teams]([TeamId])
GO

ALTER TABLE [Drivers]
ADD FOREIGN KEY([TeamId])
REFERENCES [Teams]([TeamId])
GO

ALTER TABLE [Drivers]
ADD FOREIGN KEY([CarId])
REFERENCES [Cars]([CarId])
GO

ALTER TABLE [Engineers]
ADD FOREIGN KEY([CarId])
REFERENCES [Cars]([CarId])
GO

ALTER TABLE Engineers
ADD CONSTRAINT UQ_Car_Specialization
UNIQUE (CarId, Specialization);

SELECT * FROM Teams
SELECT * FROM Boss



